name = "fsid"
uuid = "2e1f4868-8d8f-4a5f-a217-6f65c14496e6"
authors = ["Mladen Gibanica <mgcth@users.noreply.github.com> and Tomas McKelvey <tomas.mckelvey@gmail.com>"]
version = "0.1.2"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
